### ISSUE TITLE
Add libportal

### ISSUE THREAD

**Issue by leolost2605** [elementary/seeds#101]
### Problem

No idea how this work but I think `libportal1` and `libportal-gtk3-1` might have to be added after elementary/mail#882?

### Proposal

Add libportal?

**Comment by lenemter** [comment]
You probably want to update Mail's `deb-packaging` branch.

**Comment by tintou** [comment]
Added in deb-packaging branch https://github.com/elementary/mail/commit/e764cd56b1afd45e5ec4fcd47ffcd8585816e7b0

**Comment by leolost2605** [comment]
Thank you!
