### ISSUE TITLE
Add Wacom tablet plug [$50]

### ISSUE THREAD

**Issue by ma1onso** [elementary/seeds#4]
Gnome 3.28 is an amazing example, this allows configure pen and tablet.

![screenshot from 2018-09-11 12-03-06](https://user-images.githubusercontent.com/1877511/45387548-ff455800-b5db-11e8-9548-0dae2a352b21.png)

![screenshot from 2018-09-11 12-03-59](https://user-images.githubusercontent.com/1877511/45387549-ffddee80-b5db-11e8-8de1-d9eaa565b683.png)

**Comment by Alecaddd** [comment]
I started working on this by creating a dedicated standalone plug: https://github.com/Alecaddd/switchboard-plug-tablet

I'm following the structure of the Mouse & Touch plug to have different pages for Display, Stylus, and Pad Button/Ringer.
I have a couple of graphics tablets from different brands I can test to be sure it works not only with Wacom tablets.

**Comment by danirabbit** [comment]
Closing because the latest 6.0 daily includes the wacom plug

**Comment by ma1onso** [comment]
> Closing because the latest 6.0 daily includes the wacom plug

@danrabbit download link?

**Comment by danirabbit** [comment]
@ma1onso 6.0 dailies are not publicly available at this time

**Comment by awaismirza92** [comment]
Hi, when do we expect 6.0 dailies to be available publicly?
