### ISSUE TITLE
Add gnome-control-center-faces package to Odin for some handy avatars

### ISSUE THREAD

**Issue by vjr** [elementary/seeds#51]
Request to add the `gnome-control-center-faces` package to the default Odin ISO installation so that there are some pixmaps available in `/usr/share/pixmaps/faces` to select as user avatar, I usually pick the pengiun avatar for my user account pic.

**Comment by danirabbit** [comment]
There's currently nowhere that these images are exposed in the UI. So if you know about this system location to load from, I'm not sure how much of an inconvenience it is to install this package yourself

**Comment by vjr** [comment]
Makes sense. Most people will probably set their avatar to something they download or create themselves, I guess.

**Comment by ernstki** [comment]
Coming from other distros and macOS, I miss having a selection of generic avatars, even if it means having to browse to `/usr/share/pixmaps/faces` manually. So thanks, @vjr, for [cuing me in](https://ell.stackexchange.com/questions/147616/what-does-cue-in-to-mean) to which package those come from!

I'm not in love with seeing my stupid face staring back at me when I log into my computer, and the industry-standard colored monogram doesn't really help that much when it comes to differentiating between multiple accounts. I'll go for the puppy or the lightning bolt every time, if there's the choice.

Would it help to point the file picker for the "User Accounts" switchboard at `/usr/share/pixmaps/faces` by default, if it exists?

**Comment by danirabbit** [comment]
There's an open feature request against user accounts for stock avatar images here: https://github.com/elementary/switchboard-plug-useraccounts/issues/185
