### ISSUE TITLE
flatpak-builder 1.0.10 causing hard locks on OS 6.1

### ISSUE THREAD

**Issue by cassidyjames** [elementary/seeds#94]
I've heard this report from a few app developers in the community Slack and I've hit it myself when building apps on OS 6.1: flatpak-builder hard locks my machine when building an app (in my case, Music, but @avojak had trouble with his app, too).

Installing and using a newer flatpak-builder with `flatpak install flathub org.flatpak.Builder` seems to resolve it, so it appears to be an issue in the flatpak-builder package in the repos. As long as we're recommending developers use `flatpak-builder` on OS 6.1, we should figure out if we can backport a newer version or instead recommend using the Flatpak version.

**Comment by avojak** [comment]
Using the latest flatpak-builder installed from their Flatpak is what worked for me as well. No idea what the problem is, rarely crashed in the same place twice.

**Comment by cassidyjames** [comment]
It looks like `1.2.2-2flatpak1~20.04` was pulled into the OS patches PPA recently, so I believe this _should_ be resolved.
