### ISSUE TITLE
Consider shipping Ideogram by default

### ISSUE THREAD

**Issue by colinkiama** [elementary/seeds#97]
### Problem

Currently, there is no easy way of inputting emoji on every app. The "insert emoji" option in the right-click menu only shows up in GTK apps but even in GTK apps, it's not always available.

While to some, this may not seem like a big deal, emoji are one of the best ways to express ourselves universally. Sometimes words alone can't portray the full meaning behind a message.

### Proposal

[Ideogram](https://github.com/cassidyjames/ideogram) solves this issue on elementary OS. It allows us to access a panel of emoji via a keyboard shortcut similar to [Windows (Windows + .)](https://support.microsoft.com/en-us/windows/windows-keyboard-tips-and-tricks-588e0b72-0fff-6d3f-aeee-6e5116097942) and [macOS (Command + Space-bar)](https://support.apple.com/en-gb/HT201236).

Shipping Ideogram (or a fork of it) with a keyboard shortcut preassigned will make things a lot easier for people who do want to use emoji on elementary OS. 

### Prior Art (Optional)

Windows 11 Emoji Panel:
![Emoji Panel Windows 11](https://user-images.githubusercontent.com/16501024/168244593-f6f3fde7-d03a-410f-a488-d4de543ed5d6.png)

**Comment by ernstki** [comment]
@colinkiama What was the resolution? I have this distinct feeling like in an alternate timeline <kbd>⌘</kbd>+<kbd>.</kbd> used to call up some kind of built-in doorhanger-style popup emoji picker, but it doesn't seem to anymore (in 7.x anyway). Maybe it only worked in Gtk apps, I dunno.

Ideogram still _builds_ on 7.x, and I found where in the code you set the shortcut, but the shortcut doesn't seem to bring it up anymore, and when you launch it manually, it doesn't actually seem to do its job of inserting emojis.

**Update**: Just mashing keys randomly, I discovered that <kbd>Ctrl</kbd>+<kbd>.</kbd> seems to work, similar to how <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> lets you insert Unicode characters by codepoint. Seems essentially undocumented, though. Use <kbd>Space</kbd> to cycle through matches, and <kbd>Enter</kbd> to insert; <kbd>Esc</kbd> cancels the prompt. Seems to mostly work in Qt apps as well.

![A short GIF screencast of the iBus (?) shortcuts Ctrl+. and Ctrl+; being used to insert thumbs-up and thumbs-down emoji](https://github.com/user-attachments/assets/c38b6a50-a0f3-4256-8bcd-aa2e7a377fe5)

The shortcut <kbd>Ctrl</kbd>+<kbd>;</kbd> _also_ works, but it seems there's a lot of contention over these shortcuts, so I'd expect things to be different (again) in elementary OS 8.x.

I _believe_ [iBus is providing this](https://wiki.archlinux.org/title/IBus#Emoji_input) for me. It doesn't seem to work in "demo mode" using the bootable ISO. I guess [it's](https://github.com/elementary/settings-desktop/issues/144#issuecomment-425170989) [just](https://www.reddit.com/r/gnome/comments/xxape5/comment/irb7cuc/) [complicated](https://github.com/ibus/ibus/commit/1520c39d0d6036da725fcecd932883be3f3d3575).
